#!/usr/bin/env python3


# Author: Ryan Tiffany
# Copyright (c) 2024
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
from rich.prompt import Prompt, Confirm
import click
import db
import setup

CONFIG_DIR_DEFAULT = os.path.expanduser('~/.config/prjkt')

def check_editor():
    # Checking if EDITOR environment variable is set
    if os.environ.get('EDITOR') is None:
        print("EDITOR is not set.")
        print("Although `prjkt` is initialized, you will not be able to add, copy or edit projects. Please set EDITOR environment variable to your preferred editor.")

@click.group()
def cli():
    pass

@cli.command()
def config(): 
    """Configure prjkt"""
    setup.setup_config()

cli.add_command(config)


@cli.command()
@click.argument("name")
@click.option("-p", "--path", default=None, help="Project path on disk")
@click.option("-m", "--managed", default=True, help="Whether to create start/stop scripts")              
@click.option("-v", "--version", default="0.1.0")
@click.option("-l", "--language", default="None")  
@click.option("-t", "--tags", default="")
def new_project(name, path, managed, version, language, tags):
    """Creates a new project"""
    project = {
        "name": name,
        "path": path,
        "managed": managed, 
        "version": version,
        "language": language,
        "tags": tags.split(",")
    }
    
    db.create_project(project)
    click.echo(f"Created project: {name}")

cli.add_command(new_project)

@click.command()
@click.option("-n", "--name", default=None, help="Project name")
def view_projects():
    for proj in db.get_projects():
        click.echo(f"{proj['name']} ({proj['language']}) - {proj['path']}")

cli.add_command(view_projects)

if __name__ == "__main__":
    cli()










